ABSTRACT_TESTS = [
    {
        "name": "Abstract Test 1",
        "id": "/ats/core/http",
        "requirements": ["/req/core/http"],
        "purpose": "Validate that the resource paths advertised through the API conform with HTTP 1.1 and, "
                   "where approprate, TLS",
    },
    {
        "name": "Abstract Test 2",
        "id": "/ats/core/crs84",
        "requirements": ["/req/core/crs84"],
        "purpose": "Validate that all spatial geometries provided through the API are in the CRS84 spatial "
                   "reference system unless otherwise requested by the client",
    },
    {
        "name": "Abstract Test 3",
        "id": "/ats/core/root-op",
        "requirements": ["/req/core/root-op"],
        "purpose": "Validate that a landing page can be retrieved from the expected location",
    },
    {
        "name": "Abstract Test 4",
        "id": "/ats/core/root-success",
        "requirements": ["/req/core/root-success"],
        "purpose": "Validate that the landing page complies with the require structure and contents",
    },
    {
        "name": "Abstract Test 5",
        "id": "/ats/core/api-definition-op",
        "requirements": ["/req/core/api-definition-op"],
        "purpose": "Validate that the API Definition document can be retrieved from the expected location",
    },
    {
        "name": "Abstract Test 6",
        "id": "/ats/core/api-definition-success",
        "requirements": ["/req/core/api-definition-success"],
        "purpose": "Validate that the API Definition complies with the required structure and contents",
    },
    {
        "name": "Abstract Test 7",
        "id": "/ats/core/conformance-op",
        "requirements": ["/req/core/conformance-op"],
        "purpose": "Validate that a Conformance Declaration can be retrieved from the expected location",
    },
    {
        "name": "Abstract Test 8",
        "id": "/ats/core/conformance-success",
        "requirements": ["/req/core/conformance-success"],
        "purpose": "Validate that the Conformance Declaration response complies with the required structure "
                   "and contents",
    },
    {
        "name": "Abstract Test 9",
        "id": "/ats/core/fc-md-op",
        "requirements": ["/req/core/fc-md-op"],
        "purpose": "Validate that information about the Collections can be retrieved from the expected location",
    },
    {
        "name": "Abstract Test 10",
        "id": "/ats/core/fc-md-success",
        "requirements": ["/req/core/fc-md-success", "/req/core/crs84"],
        "purpose": "Validate that the Collections content complies with the required structure and contents",
    },
    {
        "name": "Abstract Test 11",
        "id": "/ats/core/sfc-md-op",
        "requirements": ["/req/core/sfc-md-op"],
        "purpose": "Validate that the Collection content can be retrieved from the expected location",
    },
    {
        "name": "Abstract Test 12",
        "id": "/ats/core/sfc-md-success",
        "requirements": ["/req/core/sfc-md-success"],
        "purpose": "Validate that the Collection content complies with the required structure and contents",
    },
    {
        "name": "Abstract Test 13",
        "id": "/ats/core/fc-op",
        "requirements": ["/req/core/fc-op"],
        "purpose": "Validate that features can be identified and extracted from a Collection using query parameters",
    },
    {
        "name": "Abstract Test 14",
        "id": "/ats/core/fc-bbox-definition",
        "requirements": ["/req/core/fc-bbox-definition"],
        "purpose": "Validate that the bounding box query parameters are constructed correctly",
    },
    {
        "name": "Abstract Test 15",
        "id": "/ats/core/fc-bbox-response",
        "requirements": ["/req/core/fc-bbox-response"],
        "purpose": "Validate that the bounding box query parameters are processed corrrectly",
    },
    {
        "name": "Abstract Test 16",
        "id": "/ats/core/fc-limit-definition",
        "requirements": ["/req/core/fc-limit-definition"],
        "purpose": "Validate that the bounding box query parameters are constructed corrrectly",
    },
    {
        "name": "Abstract Test 17",
        "id": "/ats/core/fc-limit-response",
        "requirements": ["/req/core/fc-limit-response"],
        "purpose": "Validate that the limit query parameters are processed correctly",
    },
    {
        "name": "Abstract Test 18",
        "id": "/ats/core/fc-time-definition",
        "requirements": ["/req/core/fc-time-definition"],
        "purpose": "Validate that the dateTime query parameters are constructed correctly",
    },
    {
        "name": "Abstract Test 19",
        "id": "/ats/core/fc-time-response",
        "requirements": ["/req/core/fc-time-response"],
        "purpose": "Validate that the dataTime query parameters are processed correctly",
    },
    {
        "name": "Abstract Test 20",
        "id": "/ats/core/query-param-invalid",
        "requirements": ["/req/core/query-param-invalid"],
        "purpose": "Validate that the API correctly deals with invalid query parameters",
    },
    {
        "name": "Abstract Test 21",
        "id": "/ats/core/query-param-unknown",
        "requirements": ["/req/core/query-param-unknown"],
        "purpose": "Validate that the API correctly deals with unknown query parameters",
    },
    {
        "name": "Abstract Test 22",
        "id": "/ats/core/fc-response",
        "requirements": ["/req/core/fc-response"],
        "purpose": "Validate that the Feature Collections complies with the require structure and contents",
    },
    {
        "name": "Abstract Test 23",
        "id": "/ats/core/fc-links",
        "requirements": ["/req/core/fc-links"],
        "purpose": "Validate that the required links are included in the Collections document",
    },
    {
        "name": "Abstract Test 24",
        "id": "/ats/core/fc-timeStamp",
        "requirements": ["/req/core/fc-timeStamp"],
        "purpose": "Validate the timeStamp parameter returned with a Features response",
    },
    {
        "name": "Abstract Test 25",
        "id": "/ats/core/fc-numberMatched",
        "requirements": ["/req/core/fc-numberMatched"],
        "purpose": "Validate the numberMatched parameter returned with a Features response",
    },
    {
        "name": "Abstract Test 26",
        "id": "/ats/core/fc-numberReturned",
        "requirements": ["/req/core/fc-numberReturned"],
        "purpose": "Validate the numberReturned parameter returned with a Features response",
    },
    {
        "name": "Abstract Test 27",
        "id": "/ats/core/f-op",
        "requirements": ["/req/core/f-op"],
        "purpose": "Validate that a feature can be retrieved from the expected location",
    },
    {
        "name": "Abstract Test 28",
        "id": "/ats/core/f-success",
        "requirements": ["/req/core/f-success"],
        "purpose": "Validate that the Feature complies with the required structure and contents",
    },
    {
        "name": "Abstract Test 29",
        "id": "/ats/core/f-links",
        "requirements": ["/req/core/f-links"],
        "purpose": "Validate that the required links are included in a Feature",
    },
    {
        "name": "Abstract Test 30",
        "id": "/ats/geojson/definition",
        "requirements": ["/req/geojson/definition"],
        "purpose": "Verify support for JSON and GeoJSON",
    },
    {
        "name": "Abstract Test 31",
        "id": "/ats/geojson/content",
        "requirements": ["/req/geojson/content"],
        "purpose": "Verify the content of a GeoJSON document given an input document and schema",
    },
    {
        "name": "Abstract Test 32",
        "id": "/ats/gmlsf0/definition",
        "requirements": ["/req/gmlsf0/definition"],
        "purpose": "Verify support for GML Simple Features level 0",
    },
    {
        "name": "Abstract Test 33",
        "id": "/ats/gmlsf0/content",
        "requirements": ["/req/gmlsf0/content"],
        "purpose": "Verify the content of an GML Simple Features 0 document given an input document and schema",
    },
    {
        "name": "Abstract Test 34",
        "id": "/ats/gmlsf2/definition",
        "requirements": ["/req/gmlsf2/definition"],
        "purpose": "Verify support for GML Simple Features level 2",
    },
    {
        "name": "Abstract Test 35",
        "id": "/ats/gmlsf2/content",
        "requirements": ["/req/gmlsf2/content"],
        "purpose": "Verify the content of an GML Simple Features level 2 document given an input document and schema",
    },
    {
        "name": "Abstract Test 36",
        "id": "/ats/html/definition",
        "requirements": ["/req/html/definition"],
        "purpose": "Verify support for HTML",
    },
    {
        "name": "Abstract Test 37",
        "id": "/ats/html/content",
        "requirements": ["/req/html/content"],
        "purpose": "Verify the content of an HTML document given an input document and schema",
    },
    {
        "name": "Abstract Test 38",
        "id": "/ats/oas30/completeness",
        "requirements": ["/req/oas30/completeness"],
        "purpose": "Verify the completeness of an OpenAPI document",
    },
    {
        "name": "Abstract Test 39",
        "id": "/ats/oas30/exceptions-codes",
        "requirements": ["/req/oas30/exceptions-codes"],
        "purpose": "Verify that the OpenAPI document fully describes potential exception codes",
    },
    {
        "name": "Abstract Test 40",
        "id": "/ats/oas30/oas-definition-1",
        "requirements": ["/req/oas30/oas-definition-1"],
        "purpose": "Verify that JSON and HTML versions of the OpenAPI document are available",
    },
    {
        "name": "Abstract Test 41",
        "id": "/ats/oas30/oas-definition-2",
        "requirements": ["/req/oas30/oas-definition-2"],
        "purpose": "Verify that the OpenAPI document is valid JSON",
    },
    {
        "name": "Abstract Test 42",
        "id": "/ats/oas30/oas-impl",
        "requirements": ["/req/oas30/oas-impl"],
        "purpose": "Verify that all capabilities specified in the OpenAPI definition are implemented by the API",
    },
    {
        "name": "Abstract Test 43",
        "id": "/ats/oas30/security",
        "requirements": ["/req/oas30/security"],
        "purpose": "Verify that any authentication protocols implemented by the API are documented in the "
                   "OpenAPI document",
    },
]
